### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by Liryna** [elfring/BtYacc#1]
I suggest to reuse a higher level build system than [your current small make](https://github.com/elfring/BtYacc/blob/master/Makefile#L2) file so that powerful checks for software features will become easier.
-  [CMake](https://cmake.org/)
- [Autotools](http://www.gnu.org/software/autoconf/autoconf.html)

**Comment by elfring** [comment]
How do you think about to [look at the provided build script](https://github.com/elfring/BtYacc/commit/74efbf0d3c6e33e8a7da306dcc3d6c002bbc7ba9) (and [the development branch "route1"](https://github.com/elfring/BtYacc/commits/route1)) once more?

**Comment by Liryna** [comment]
Therefor you should also update the [Readme ](https://github.com/elfring/BtYacc/blob/route1/README#L559) of the [the development branch "route1"](https://github.com/elfring/BtYacc/commits/route1) to reflect the changes

**Comment by elfring** [comment]
Would you like to try the provided software out?

**Comment by Liryna** [comment]
It would be more simple that the owner of the commit rebase it directly with Readme to keep a 
clean history.

**Comment by elfring** [comment]
I prefer to [avoid rebasing](https://git-scm.com/book/en/v2/Git-Branching-Rebasing#The-Perils-of-Rebasing). Are you looking for more software improvements?

**Comment by Liryna** [comment]
Rebasing will not affect the master after merge.
I hope this remaining fix can be considered once more later.

**Comment by zosrothko** [comment]
I disagree to use autotool & CMake... This prevents to port BtYacc easily on Cygwin and Windows...

**Comment by Liryna** [comment]
I agree @zosrothko , CMake should be used.
